// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQlc2s5y65XqZuRzrzAxjTyJLEj6QbVy4',
    appId: '1:181772489544:web:31e60022c5a447e52d597d',
    messagingSenderId: '181772489544',
    projectId: 'k9ops-2f11f',
    authDomain: 'k9ops-2f11f.firebaseapp.com',
    databaseURL: 'https://k9ops-2f11f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'k9ops-2f11f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChrAn3oOVgxqiRGKsJ9IqfALWCywAHY2U',
    appId: '1:181772489544:android:dd7da92e5844dcb72d597d',
    messagingSenderId: '181772489544',
    projectId: 'k9ops-2f11f',
    databaseURL: 'https://k9ops-2f11f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'k9ops-2f11f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKRkCLMRCUucA3X3-cMHW0TxrwM8Yp60M',
    appId: '1:181772489544:ios:e6ccc02279e9eb2a2d597d',
    messagingSenderId: '181772489544',
    projectId: 'k9ops-2f11f',
    databaseURL: 'https://k9ops-2f11f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'k9ops-2f11f.firebasestorage.app',
    iosBundleId: 'com.example.board',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKRkCLMRCUucA3X3-cMHW0TxrwM8Yp60M',
    appId: '1:181772489544:ios:e6ccc02279e9eb2a2d597d',
    messagingSenderId: '181772489544',
    projectId: 'k9ops-2f11f',
    databaseURL: 'https://k9ops-2f11f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'k9ops-2f11f.firebasestorage.app',
    iosBundleId: 'com.example.board',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQlc2s5y65XqZuRzrzAxjTyJLEj6QbVy4',
    appId: '1:181772489544:web:5e4b32a25d19610b2d597d',
    messagingSenderId: '181772489544',
    projectId: 'k9ops-2f11f',
    authDomain: 'k9ops-2f11f.firebaseapp.com',
    databaseURL: 'https://k9ops-2f11f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'k9ops-2f11f.firebasestorage.app',
  );

}